### ISSUE TITLE
INSERT a txt-ben hibás

### ISSUE THREAD

**Issue by nkornel** [Bazsmagister/Ovoda#1]
2.
INSERT INTO students VALUES
 (1, 'Horváth', 'Péter', 'alma', 4);

INSERT INTO students VALUES
 (NULL, 'Kovács', 'Júlia', 'birs', 4);

**Comment by Bazsmagister** [comment]
INSERT INTO students (first_name, last_name, sign, age) 
VALUES ('Horváth', 'Péter', 'alma', '4');

INSERT INTO students (first_name, last_name, sign, age)
VALUES ('Kovács', 'Júlia', 'birs', '4');
